# Generated by Django 3.2.1 on 2021-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecone', '0002_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titlea',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
